// <auto-generated />
namespace CheckRayApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_UserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_UserId));
        
        string IMigrationMetadata.Id
        {
            get { return "202310170017543_add_UserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
