//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckRay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int bookingId { get; set; }
        public Nullable<int> doctorId { get; set; }
        public int patientId { get; set; }
        public int facilityId { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> reviewId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Review Review { get; set; }
    }
}
